# Generated by Django 4.1.7 on 2023-02-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_item', models.JSONField()),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
