# Generated by Django 4.1.7 on 2023-02-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_item',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
