# Generated by Django 4.1.7 on 2023-02-16 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0003_rename_uid_search_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid'),
        ),
    ]
