# Generated by Django 4.1.7 on 2023-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0005_search_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('tittle', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
