# Generated by Django 4.1.7 on 2023-02-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundable', models.BooleanField()),
                ('validating_airline', models.CharField(max_length=255)),
                ('pricing', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_airline', models.CharField(max_length=255)),
                ('marketing_airline', models.CharField(max_length=255)),
                ('flight_number', models.IntegerField()),
                ('equipment', models.CharField(max_length=255)),
                ('dep', models.JSONField()),
                ('arr', models.JSONField()),
                ('baggage', models.CharField(max_length=255)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.flight')),
            ],
        ),
    ]
