# Generated by Django 4.1.7 on 2023-02-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_validating_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.flight'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='flight_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
