# Generated by Django 4.1.7 on 2023-02-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_price_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pricing',
        ),
        migrations.AlterField(
            model_name='booking',
            name='refundable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
