# Generated by Django 4.1.7 on 2023-02-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_pricing_alter_booking_refundable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
